//
//  ImageList.swift
//  MyCalendarOfMuscle
//
//  Created by 矢嶋丈 on 2020/10/19.
//

import Foundation
import UIKit

//63通り
//1set(7通り)
let udeImg = UIImage(named: "ude")?.resized(toWidth: 20)
let kataImg = UIImage(named: "kata")?.resized(toWidth: 20)
let muneImg = UIImage(named: "mune")?.resized(toWidth: 20)
let haraImg = UIImage(named: "hara")?.resized(toWidth: 20)
let senakaImg = UIImage(named: "senaka")?.resized(toWidth: 20)
let ashiImg = UIImage(named: "ashi")?.resized(toWidth: 20)
let yuuImg = UIImage(named: "yuu")?.resized(toWidth: 20)

//2set(21通り)
let udekata = UIImage(named: "udekata")?.resized(toWidth: 38)
let udemune = UIImage(named: "udemune")?.resized(toWidth: 38)
let udehara = UIImage(named: "udehara")?.resized(toWidth: 38)
let udesenaka = UIImage(named: "udesenaka")?.resized(toWidth: 38)
let udeashi = UIImage(named: "udeashi")?.resized(toWidth: 38)
let udeyuu = UIImage(named: "udeyuu")?.resized(toWidth: 38)
let katamune = UIImage(named: "katamune")?.resized(toWidth: 38)
let katahara = UIImage(named: "katahara")?.resized(toWidth: 38)
let katasenaka = UIImage(named: "katasenaka")?.resized(toWidth: 38)
let kataashi = UIImage(named: "kataashi")?.resized(toWidth: 38)
let katayuu = UIImage(named: "katayuu")?.resized(toWidth: 38)
let munehara = UIImage(named: "munehara")?.resized(toWidth: 38)
let munesenaka = UIImage(named: "munesenaka")?.resized(toWidth: 38)
let muneashi = UIImage(named: "muneashi")?.resized(toWidth: 38)
let muneyuu = UIImage(named: "muneyuu")?.resized(toWidth: 38)
let harasenaka = UIImage(named: "harasenaka")?.resized(toWidth: 38)
let haraashi = UIImage(named: "haraashi")?.resized(toWidth: 38)
let harayuu = UIImage(named: "harayuu")?.resized(toWidth: 38)
let senakaashi = UIImage(named: "senakaashi")?.resized(toWidth: 38)
let senakayuu = UIImage(named: "senakayuu")?.resized(toWidth: 38)
let ashiyuu = UIImage(named: "ashiyuu")?.resized(toWidth: 38)


//3set(35通り)
let udekatamune = UIImage(named: "udekatamune")?.resized(toWidth: 53)
let udekatahara = UIImage(named: "udekatahara")?.resized(toWidth: 53)
let udekatasenaka = UIImage(named: "udekatasenaka")?.resized(toWidth: 53)
let udekataashi = UIImage(named: "udekataashi")?.resized(toWidth: 53)
let udekatayuu = UIImage(named: "udekatayuu")?.resized(toWidth: 53)
let udemunehara = UIImage(named: "udemunehara")?.resized(toWidth: 53)
let udemunesenaka = UIImage(named: "udemunesenaka")?.resized(toWidth: 53)
let udemuneashi = UIImage(named: "udemuneashi")?.resized(toWidth: 53)
let udemuneyuu = UIImage(named: "udemuneyuu")?.resized(toWidth: 53)
let udeharasenaka = UIImage(named: "udeharasenaka")?.resized(toWidth: 53)
let udeharaashi = UIImage(named: "udeharaashi")?.resized(toWidth: 53)
let udeharayuu = UIImage(named: "udeharayuu")?.resized(toWidth: 53)
let udesenakaashi = UIImage(named: "udesenakaashi")?.resized(toWidth: 53)
let udesenakayuu = UIImage(named: "udesenakayuu")?.resized(toWidth: 53)
let udeashiyuu = UIImage(named: "udeashiyuu")?.resized(toWidth: 53)
let katamunehara = UIImage(named: "katamunehara")?.resized(toWidth: 53)
let katamunesenaka = UIImage(named: "katamunesenaka")?.resized(toWidth: 53)
let katamuneashi = UIImage(named: "katamuneashi")?.resized(toWidth: 53)
let katamuneyuu = UIImage(named: "katamuneyuu")?.resized(toWidth: 53)
let kataharasenaka = UIImage(named: "kataharasenaka")?.resized(toWidth: 53)
let kataharaashi = UIImage(named: "kataharaashi")?.resized(toWidth: 53)
let kataharayuu = UIImage(named: "kataharayuu")?.resized(toWidth: 53)
let katasenakaashi = UIImage(named: "katasenakaashi")?.resized(toWidth: 53)
let katasenakayuu = UIImage(named: "katasenakayuu")?.resized(toWidth: 53)
let kataashiyuu = UIImage(named: "kataashiyuu")?.resized(toWidth: 53)
let muneharasenaka = UIImage(named: "muneharasenaka")?.resized(toWidth: 53)
let muneharaashi = UIImage(named: "muneharaashi")?.resized(toWidth: 53)
let muneharayuu = UIImage(named: "muneharayuu")?.resized(toWidth: 53)
let munesenakaashi = UIImage(named: "munesenakaashi")?.resized(toWidth: 53)
let munesenakayuu = UIImage(named: "munesenakayuu")?.resized(toWidth: 53)
let muneashiyuu = UIImage(named: "muneashiyuu")?.resized(toWidth: 53)
let harasenakaashi = UIImage(named: "harasenakaashi")?.resized(toWidth: 53)
let harasenakayuu = UIImage(named: "harasenakayuu")?.resized(toWidth: 53)
let haraashiyuu = UIImage(named: "haraashiyuu")?.resized(toWidth: 53)
let senakaashiyuu = UIImage(named: "senakaashiyuu")?.resized(toWidth: 53)
